services:
  # Oracle Database 23c Free (Requisito da Vaga)
  oracle-db:
    image: container-registry.oracle.com/database/free:latest
    container_name: edufin-oracle
    ports:
      - '1521:1521'
    environment:
      - ORACLE_PWD=SeniorPass123!
    volumes:
      - oracle_data:/opt/oracle/oradata # Named Volume evita problema de permiss√£o no WSL
    healthcheck: # Vital para o Spring esperar o banco subir
      test: ['CMD', '/opt/oracle/runOracle.sh', 'check']
      interval: 20s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 4G # Importante no seu .wslconfig de 8GB

  # Kafka (Modo KRaft - Sem Zookeeper para economizar RAM)
  kafka:
    image: bitnami/kafka:3.6
    container_name: edufin-kafka
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    volumes:
      - kafka_data:/bitnami/kafka

  # RabbitMQ (Com Plugin de Management)
  rabbitmq:
    image: rabbitmq:3-management
    container_name: edufin-rabbitmq
    ports:
      - '5672:5672' # Protocolo
      - '15672:15672' # Interface Web
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  oracle_data:
  kafka_data:
  rabbitmq_data:
